# Generated by Django 4.1 on 2022-08-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=64)),
                ('Edad', models.IntegerField()),
                ('Cumpleaños', models.DateField()),
            ],
        ),
    ]
